apiVersion: apps/v1
kind: Deployment
metadata:
  name: direct-pod
  namespace: direct-pod
  labels:
    app: direct-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: direct-pod
  template:
    metadata:
      labels:
        app: direct-pod
#      annotations:
#        alpha.image-policy.k8s.io/break-glass: "true"
    spec:
      containers:
      - name: direct-pod
        image: nginx
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
            memory: "2Gi"
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false
          privileged: false