apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-without-limits
  labels:
    app: pod-without-limits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-without-limits
  template:
    metadata:
      labels:
        app: pod-without-limits
      annotations:
        alpha.image-policy.k8s.io/break-glass: "true"
    spec:
      containers:
      - name: pod-without-limits
        image: gcr.io/anthos-customer-demos/hello-app:35f08e2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
            memory: "1Gi"
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false
          privileged: false