apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-container
  labels:
    app: privileged-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privileged-container
  template:
    metadata:
      labels:
        app: privileged-container
      annotations:
        alpha.image-policy.k8s.io/break-glass: "true"
    spec:
      containers:
      - name: privileged-container
        image: nginx
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "1Gi"
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false
          privileged: true #false